# Generated by Django 4.2.10 on 2024-04-27 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
