# Generated by Django 5.0.4 on 2024-05-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.CharField(blank=True, choices=[('B.Tech', 'B.Tech'), ('MBA', 'MBA'), ('BSC', 'BSC')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('cse', 'Computer Science and Engineering'), ('ece', 'Electronics and Communication Engineering'), ('eee', 'Electrical and Electronics Engineering'), ('mech', 'Mechanical Engineering')], max_length=100, null=True),
        ),
    ]
