# Generated by Django 5.0.4 on 2024-04-27 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='categories.category')),
                ('staff_organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_events', to=settings.AUTH_USER_MODEL)),
                ('student_organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
