# Generated by Django 5.0.4 on 2024-04-28 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='staff_organizer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='student_organizer',
        ),
        migrations.AddField(
            model_name='event',
            name='staff_organizer',
            field=models.ManyToManyField(related_name='staff_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='student_organizer',
            field=models.ManyToManyField(related_name='student_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
